version: '3.9'
services:
  db:
    image: postgres:15
    restart: always
    environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
    ports: 
      - "5432:5432"
    volumes:
      - ./createdatabases.sql:/docker-entrypoint-initdb.d/createdatabases.sql
    networks:
      - tropical-network
  project:
    image: thauans/project
    build: 
      context: ./project
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    depends_on:
      - tropical
      - email
  tropical:
    image: thauans/tropical
    restart: always
    build: ./Tropical
    working_dir: /Tropical
    environment:
      SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/tropical
    ports: 
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - tropical-network
  email:
    image: thauans/email
    restart: always
    build: ./email
    working_dir: /email
    environment:
      SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/email
    ports:
      - 81:8082
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - tropical-network
networks:
  tropical-network:
    driver: bridge