--INSERT INTO `tb_users` (`user_id`, `username`, `password`) VALUES
--  (UNHEX(REPLACE(UUID(), '-', '')), 'thauan', 'password1'),
--  (UNHEX(REPLACE(UUID(), '-', '')), 'empresa2', 'password2'),
--  (UNHEX(REPLACE(UUID(), '-', '')), 'admin', 'password3'),
--  (UNHEX(REPLACE(UUID(), '-', '')), 'thau', 'password4');
