--INSERT INTO `tb_users` (`user_id`, `username`, `password`) VALUES
--  (UUID_TO_BIN(UUID()), 'thauan', '123'),
--  (UUID_TO_BIN(UUID()), 'empresa2', '123'),
--  (UUID_TO_BIN(UUID()), 'admin', '123'),
--  (UUID_TO_BIN(UUID()), 'thau', '123');
