server:
  port: 80
cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://erudio.com.br
file:
  upload-dir: /Users/nilza/OneDrive/Área de Trabalho/upload-dir
security:
  jwt:
    token:
      secret-key:53cr37
      expire-legth:3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tropical?useTimezone=true&serverTimezone=UTC
    username: ${USER}
    password: ${PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none 
    show-sql: false
  servlet:
     multipart:
       enabled: true
       file-size-threshold: 2KB
       max-file-size: 200MB
       max-request-size: 215MB
springdoc:
  pathsToMatch:
  - /auth/**
  - /api/**/v1/**
  swagger-ui:
    use-root-path: true


