services:
  mysql:
    image: mysql
    ports:
     - "3306:3306"
    expose:
      - "3306" 
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Domingos.noemia1
      - MYSQL_DATABASE=tropical
      - MYSQL_ROOT_PASSWORD=123